Algoritmo "OlaMundo!"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Pedir para o usuário digitar a frase; Olá, Mundo!
// Autor(a)    : Anderson Silva
// Data atual  : 14/08/2024
Var
    primeiraMensagem, frase: Caracter
Inicio
      Escreval ("Minha primeira mensagem.")
      Escreval ("")
      Escreval ("Qual a mensagem que todo programador tem que saber ?")
      Leia (primeiraMensagem)
      frase <- primeiraMensagem
      Escreval ("Mensagem: ",frase)
Fimalgoritmo