Algoritmo "Teste de Variável"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo tipos de dados das variáveis.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2024
Var
   nome, sexo: Caracter
   idade: Inteiro
   salario: Real
Inicio
      nome <- ("João")
      idade <- (27)
      sexo <- ("M")
      salario <- (6300.50)
      Escreval (nome , idade, " ",sexo , salario)
Fimalgoritmo