Algoritmo "ParOuImpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   :  Calcular número par ou ímpar
// Autor(a)    : Anderson Silva
// Data atual  : 02/08/2024
Var
   Numero: Inteiro
Inicio
      Escreva("Digite algum número: ")
      Leia (Numero)
      Escreval(" ")
      Se (Numero % 2 = 0) entao
         Escreva (Numero,", é Par!")
      Senao
         Escreva (Numero,", é Impar!")
      Fimse
        Escreval(" ")
Fimalgoritmo