Algoritmo "Combinacoes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo que realizar combinações entre números.
// Autor(a)    : Anderson Silva
// Data atual  : 23/09/2024
Var
   ContadorUm, ContadorDois: Inteiro
Inicio
   Para ContadorUm := 1 ate 3 faca
      Para ContadorDois := 1 ate 3 faca
         Escreval(ContadorUm, ContadorDois)
      FimPara
   FimPara
Fimalgoritmo