Algoritmo "SomadorPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo somar valor que utiliza a estrutura Para
// Autor(a)    : Anderson Silva
// Data atual  : 18/09/2024
Var
   Numero, Contador, Soma: Inteiro
Inicio
   Soma <- 0
   Para Contador <- 1 ate 5 faca
      Escreva ("Digite o valor: ")
      Leia (Numero)
      Soma <- Soma + Numero
   FimPara
   Escreval ("A soma dos valores é ", Soma)
Fimalgoritmo