Algoritmo "ContarAte10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo para realizar a contagem até 10
// Autor(a)    : Anderson Silva
// Data atual  : 22/08/2024
Var
   contador : Inteiro
Inicio
   contador <- 0
   Enquanto (contador <= 10) faca
      Escreval(contador)
      contador <- contador + 1
   FimEnquanto
   Escreval ("---------------------------------")
   Escreval ("Fim")
Fimalgoritmo
