Algoritmo "ContarZeroAteDez"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo que realiza contagem regressiva, estrutura Enquanto.
// Autor(a)    : Anderson Silva
// Data atual  : 22/08/2024
Var
   contador : Inteiro
Inicio
   contador <- 10
   Enquanto (contador >= 0) faca
      Escreval(contador)
      contador <- contador - 1
   FimEnquanto
   Escreval ("---------------------------------")
   Escreval ("Fim")
Fimalgoritmo
