Algoritmo "ProcedimentoSomar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Algoritmo que realiza a soma dos valores
// Autor(a)    : Anderson Silva
// Data atual  : 24/09/2024
Var
   X, Y: Inteiro
Procedimento Soma(A, B: Inteiro)
Inicio
Escreval("Recebi o valor ",A)
Escreval("Recebi o valor ",B)
Escreval("A soma entre os dois =", A + B)
FimProcedimento
Inicio
   X <- 5
   Y <- 3
   Soma (X, Y)
Fimalgoritmo