Algoritmo "ContadorNumerico"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Solicitar a leitura de 10 números.
// Autor(a)    : Anderson Silva
// Data atual  : 16/09/2024
Var
   contador, numero: Inteiro
Inicio
      contador <- 1
      Enquanto (contador <= 10) faca
               Escreva ("Digite o ", contador, "o. valor: ")
               Leia (numero)
               contador <- contador + 1
      FimEnquanto
Fimalgoritmo